rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0

env:
  - RAILS=4-0-stable
  - RAILS=3-2-stable
  - RAILS=3-1-stable
  - RAILS=3-0-stable

matrix:
  exclude:
    - rvm: 1.8.7
      env: RAILS=4-0-stable
